[tool.poetry]
name = "qsa-api"
version = "0.0.0"
description = "QGIS Server Administration"
authors = ["Paul Blottiere <blottiere.paul@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<4"
flask = "3.0.0"
click = "8.1.7"
pyyaml = "^6.0.1"
jsonschema = "^4.21.1"
boto3 = "^1.34.123"

rasterio = "^1.3.10"
debugpy = "^1.8.12"
gunicorn = "^23.0.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
'qsa' = 'qsa_api.app:run'
